#!/bin/bash
# Ralph Continuity Hook - Saves iteration state before compaction
# Prevents loss of iteration history during context compression
# Location: /Users/quartershots/Source/.claude/hooks/ralph-continuity.sh

set -euo pipefail

CLAUDE_DIR="/Users/quartershots/Source/.claude"
THOUGHTS_DIR="$CLAUDE_DIR/thoughts"
RALPH_STATE=".claude/ralph-loop.local.md"
LEDGER="$THOUGHTS_DIR/RALPH_LEDGER.md"

# Read hook input
INPUT=$(cat)

# Only run if Ralph loop is active
[[ ! -f "$RALPH_STATE" ]] && exit 0

# Parse iteration from Ralph state
ITERATION=$(sed -n 's/^iteration: //p' "$RALPH_STATE" 2>/dev/null || echo "0")
PROMPT=$(awk '/^---$/{i++; next} i>=2' "$RALPH_STATE" 2>/dev/null | head -5)

# Get transcript path for context extraction
TRANSCRIPT_PATH=$(echo "$INPUT" | jq -r '.transcript_path // empty')

# Extract recent activity from git
RECENT_FILES=$(git diff --name-only HEAD~1 2>/dev/null | head -10 || echo "No git changes")
RECENT_COMMITS=$(git log --oneline -3 2>/dev/null || echo "No commits")

# Extract blockers/decisions from last assistant message if transcript available
BLOCKERS=""
DECISIONS=""
if [[ -n "$TRANSCRIPT_PATH" ]] && [[ -f "$TRANSCRIPT_PATH" ]]; then
  LAST_MSG=$(grep '"role":"assistant"' "$TRANSCRIPT_PATH" 2>/dev/null | tail -1 | jq -r '.message.content | map(select(.type == "text")) | map(.text) | join("\n")' 2>/dev/null || echo "")

  # Extract blockers (lines containing error, fail, block, issue, problem)
  BLOCKERS=$(echo "$LAST_MSG" | grep -i "error\|fail\|block\|issue\|problem\|cannot\|unable" | head -5 || echo "")

  # Extract decisions (lines containing decided, chose, will use, going to)
  DECISIONS=$(echo "$LAST_MSG" | grep -i "decided\|chose\|will use\|going to\|approach\|strategy" | head -5 || echo "")
fi

# Initialize ledger if doesn't exist
if [[ ! -f "$LEDGER" ]]; then
  cat > "$LEDGER" << 'EOF'
# Ralph Loop Continuity Ledger

This file preserves iteration history across compactions.
Auto-generated by ralph-continuity.sh hook.

---

EOF
fi

# Append iteration summary
cat >> "$LEDGER" << EOF

## Iteration $ITERATION - $(date '+%Y-%m-%d %H:%M:%S')

### Prompt (truncated)
\`\`\`
${PROMPT:0:200}...
\`\`\`

### Files Modified
\`\`\`
$RECENT_FILES
\`\`\`

### Recent Commits
\`\`\`
$RECENT_COMMITS
\`\`\`

### Blockers Encountered
${BLOCKERS:-"None detected"}

### Decisions Made
${DECISIONS:-"None detected"}

---

EOF

# Output confirmation (shown to user)
echo "Saved iteration $ITERATION to ledger before compaction" >&2

# Allow compaction to proceed
exit 0
