#!/bin/bash
# Pre-commit build validation for Swift/Xcode projects
# Checks that the project builds without errors before allowing commit
# Generated by /research from topic: iOS development

set -euo pipefail

# Only run if Swift files were changed
SWIFT_CHANGED=$(git diff --cached --name-only --diff-filter=ACM | grep -c '\.swift$' || true)

if [ "$SWIFT_CHANGED" -eq 0 ]; then
    exit 0
fi

# Detect project type
if ls *.xcworkspace 1>/dev/null 2>&1; then
    PROJECT_TYPE="workspace"
    PROJECT_FILE=$(ls *.xcworkspace | head -1)
elif ls *.xcodeproj 1>/dev/null 2>&1; then
    PROJECT_TYPE="project"
    PROJECT_FILE=$(ls *.xcodeproj | head -1)
elif [ -f "Package.swift" ]; then
    PROJECT_TYPE="spm"
else
    echo "No Xcode project or Package.swift found, skipping build check"
    exit 0
fi

echo "Running Swift build check..."

case $PROJECT_TYPE in
    "spm")
        swift build 2>&1 | tail -20
        ;;
    "workspace"|"project")
        # Find first scheme
        if command -v xcbeautify &>/dev/null; then
            FORMATTER="xcbeautify --quiet"
        else
            FORMATTER="tail -20"
        fi

        FLAG=$([[ "$PROJECT_TYPE" == "workspace" ]] && echo "-workspace" || echo "-project")

        set -o pipefail
        xcodebuild $FLAG "$PROJECT_FILE" \
            -scheme "$(xcodebuild $FLAG "$PROJECT_FILE" -list 2>/dev/null | sed -n '/Schemes:/,/^$/p' | sed '1d;/^$/d' | head -1 | xargs)" \
            build \
            CODE_SIGNING_ALLOWED=NO \
            2>&1 | eval "$FORMATTER"
        ;;
esac

echo "Build check passed."
