#!/bin/bash
# Self-Learning Protocol - Synthesize learnings and update MEMORY.md
#
# This script:
# 1. Checks if enough new learnings exist (threshold: 5)
# 2. Scores all learnings (signal weights + decay)
# 3. Generates a synthesis prompt from score-ranked data
# 4. Calls Claude CLI (haiku) to generate insights
# 5. Updates MEMORY.md with the results
# 6. Emits recalled signals for cited learnings
# 7. Auto-backports high-scoring learnings to skill files
#
# Usage:
#   self-learn.sh           # Normal run (respects threshold)
#   self-learn.sh --force   # Force run even below threshold
#   self-learn.sh --dry-run # Show what would happen without running
#
# Location: /Users/quartershots/Source/.claude/scripts/self-learn.sh

set -euo pipefail

# Use nvm's node for memvid operations
export PATH="${HOME}/.nvm/versions/node/v22.12.0/bin:$PATH"

CLAUDE_DIR="/Users/quartershots/Source/.claude"
SCRIPTS_DIR="${CLAUDE_DIR}/scripts"
CACHE_DIR="${CLAUDE_DIR}/cache"
MEMORY_DIR="${CLAUDE_DIR}/projects/-Users-quartershots-Source/memory"
MEMORY_FILE="${MEMORY_DIR}/MEMORY.md"
LAST_SYNTHESIS="${CACHE_DIR}/last-synthesis"
LOG_DIR="${HOME}/.claude/logs"

# Ensure directories exist
mkdir -p "$LOG_DIR" "$MEMORY_DIR" "$CACHE_DIR"

# Logging
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "${LOG_DIR}/self-learn.log"
}

# Parse args
FORCE=""
DRY_RUN=""
for arg in "$@"; do
    case "$arg" in
        --force) FORCE="--force" ;;
        --dry-run) DRY_RUN="true" ;;
    esac
done

log "Self-learning protocol started"

# Step 1: Check threshold (unless forced)
STATS=$(python3 "${SCRIPTS_DIR}/synthesize-learnings.py" --stats 2>/dev/null || echo "{}")
NEW_LEARNINGS=$(echo "$STATS" | python3 -c "import json,sys; d=json.loads(sys.stdin.read()); print(d.get('new_learnings', 0))" 2>/dev/null || echo "0")

log "New learnings since last run: ${NEW_LEARNINGS}"

if [ -z "$FORCE" ] && [ "$NEW_LEARNINGS" -lt 5 ]; then
    log "Below threshold (5). Skipping synthesis."
    exit 0
fi

# Step 2: Score all learnings
log "Scoring learnings..."
python3 "${SCRIPTS_DIR}/score-learnings.py" 2>/dev/null || log "WARNING: Scoring failed, continuing with existing scores"

# Step 3: Generate synthesis prompt
PROMPT=$(python3 "${SCRIPTS_DIR}/synthesize-learnings.py" --prompt-only $FORCE 2>/dev/null)

if [ -z "$PROMPT" ]; then
    log "No data to synthesize"
    exit 0
fi

PROMPT_TOKENS=$(echo "$PROMPT" | wc -w)
log "Generated prompt: ~${PROMPT_TOKENS} words"

if [ -n "$DRY_RUN" ]; then
    log "Dry run - would send this prompt to Claude:"
    echo "---"
    echo "$PROMPT" | head -50
    echo "..."
    exit 0
fi

# Step 4: Call Claude to synthesize (using haiku for cost efficiency)
log "Calling Claude (haiku) for synthesis..."

SYNTHESIS=$(echo "$PROMPT" | claude -p --model haiku --max-budget-usd 0.10 2>/dev/null || echo "")

if [ -z "$SYNTHESIS" ]; then
    log "ERROR: Claude synthesis failed or returned empty"
    exit 1
fi

# Step 5: Extract markdown from response
# Look for the markdown block between ```markdown and ```
MEMORY_CONTENT=$(echo "$SYNTHESIS" | sed -n '/^```markdown/,/^```$/p' | sed '1d;$d')

if [ -z "$MEMORY_CONTENT" ]; then
    # If no markdown block, use the full response
    MEMORY_CONTENT="$SYNTHESIS"
fi

# Step 6: Write to MEMORY.md
# Prepend with timestamp
FINAL_CONTENT="# Auto-Learning Insights

> Generated: $(date '+%Y-%m-%d %H:%M')
> Based on ${NEW_LEARNINGS} new learnings

${MEMORY_CONTENT}

---
*This file is auto-generated by the self-learning protocol. Manual edits may be overwritten.*
"

# Check line count
LINE_COUNT=$(echo "$FINAL_CONTENT" | wc -l)
if [ "$LINE_COUNT" -gt 200 ]; then
    log "WARNING: Output exceeds 200 lines ($LINE_COUNT). Truncating..."
    FINAL_CONTENT=$(echo "$FINAL_CONTENT" | head -195)
    FINAL_CONTENT="${FINAL_CONTENT}

... (truncated to 200 lines)
"
fi

echo "$FINAL_CONTENT" > "$MEMORY_FILE"
log "Updated MEMORY.md (${LINE_COUNT} lines)"

# Step 7: Update last synthesis timestamp
date +%s > "$LAST_SYNTHESIS"

# Step 8: Emit recalled signals for learnings cited in synthesis
log "Emitting recalled signals..."
echo "$SYNTHESIS" | python3 "${SCRIPTS_DIR}/synthesize-learnings.py" --emit-recalled --force 2>/dev/null || log "WARNING: Recalled signal emission failed"

# Step 9: Auto-backport high-scoring learnings to skill files
log "Running auto-backport..."
python3 "${SCRIPTS_DIR}/backport-learnings.py" 2>/dev/null || log "WARNING: Backport failed or script not found"

log "Self-learning protocol completed successfully"

# Output summary
echo "---"
echo "Self-learning synthesis complete:"
echo "  - New learnings processed: ${NEW_LEARNINGS}"
echo "  - MEMORY.md updated: ${MEMORY_FILE}"
echo "  - Lines written: ${LINE_COUNT}"
